import json
from typing import Any, TypeVar

import httpx
from pydantic import BaseModel, ValidationError

from core.config import settings
from core.logger import logger
from modules.llm.prompts import EXTRACT_JSON_SYSTEM_PROMPT, RAG_SYSTEM_PROMPT
from modules.llm.schemas import NoteAnalysis

T = TypeVar("T", bound=BaseModel)


async def _call_llm(
    system_prompt: str, user_prompt: str, temperature: float = 0.1
) -> dict[str, Any]:
    """Asynchronously sends a request to the LLM server and retrieves the response.

    Acts as a private core utility for all network interactions with the LLM. It
    isolates the HTTP client logic and encapsulates the raw API response into a flexible
    dictionary, ensuring forward compatibility for future feature additions
    (e.g., token usage tracking).

    Args:
        system_prompt (str): The system prompt defining the LLM's behavior and
            constraints.
        user_prompt (str): The actual user input or transcript to be processed.
        temperature (float, optional): Controls the randomness of the model's output.
            Defaults to 0.1 for deterministic tasks.

    Returns:
        dict[str, Any]: A dictionary containing:
            - 'content' (str): The primary text response generated by the model.
            - 'reasoning_content' (str): The internal reasoning or thoughts of the model
                (if applicable).
            - 'raw_message' (dict[str, Any]): The complete, unparsed message object
                from the API.

    Raises:
        httpx.HTTPError: If the network request fails or returns an
            error status code.
        KeyError: If the API response structure is malformed or
            unexpected.
    """
    payload: dict[str, Any] = {
        "model": settings.LLM_MODEL,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        "options": {
            "temperature": temperature,
            "num_ctx": settings.LLM_NUM_CTX,
        },
        "keep_alive": settings.OLLAMA_KEEP_ALIVE,
        "stream": False,
    }

    async with httpx.AsyncClient(timeout=300.0) as client:
        try:
            response = await client.post(
                f"{settings.OLLAMA_API_BASE}/chat",
                json=payload,
                headers={"Content-Type": "application/json"},
            )
            response.raise_for_status()

            response_data = response.json()
            message: dict[str, Any] = response_data.get("message", {})

            return {
                "content": message.get("content") or "",
                "reasoning_content": message.get("reasoning_content") or "",
                "raw_message": message,
            }

        except httpx.HTTPError as e:
            logger.error(f"[llm] HTTP request failed: {e}")
            raise
        except KeyError as e:
            logger.error(f"[llm] Unexpected API response structure: {e}")
            raise


async def extract_structured_data[T: BaseModel](
    user_text: str,
    response_model: type[T],
    system_prompt_template: str,
    allowed_tags: list[str],
) -> T:
    """Generic repository wrapper for extracting structured data using a local LLM.

    Automatically generates a JSON schema from the provided Pydantic model, injects it
    into the system prompt template, executes the LLM request, and strictly validates
    the returned JSON payload.

    Args:
        user_text (str): The raw input text to be analyzed.
        response_model (type[T]): The Pydantic BaseModel class defining the expected
            output structure.
        system_prompt_template (str): The template string containing a '{schema}'
            placeholder.
        allowed_tags (list[str]): Predefined tags to restrict LLM categorization.

    Returns:
        T: An instantiated and validated Pydantic object.

    Raises:
        ValueError: If the LLM returns an absolutely empty response.
        ValidationError: If output does not match the Pydantic schema.
    """
    schema_json: str = json.dumps(response_model.model_json_schema(), indent=2)
    tags_str = (
        ", ".join(allowed_tags) if allowed_tags else "None (return empty list [])"
    )
    system_prompt: str = system_prompt_template.format(
        schema=schema_json, allowed_tags=tags_str
    )

    llm_response: dict[str, Any] = await _call_llm(
        system_prompt=system_prompt, user_prompt=user_text, temperature=0.1
    )

    content: str = llm_response["content"]
    reasoning: str = llm_response.get("reasoning_content", 0) or ""

    if not content.strip():
        if reasoning.strip():
            logger.warning("[llm] Content is empty. Falling back to reasoning_content.")
            content = reasoning
        else:
            logger.error("[llm] Both content and reasoning are empty!")
            raise ValueError("LLM returned absolutely empty response.")

    clean_content: str = (
        content.strip().removeprefix("```json").removesuffix("```").strip()
    )

    try:
        return response_model.model_validate_json(clean_content)
    except ValidationError as e:
        logger.error(
            f"[llm] Pydantic validation failed for {response_model.__name__}: "
            f"{e.errors()}"
        )
        logger.debug(f"[llm] Raw LLM output: {content}")
        raise


async def analyze_transcript(transcript: str, allowed_tags: list[str]) -> NoteAnalysis:
    """Extracts business entities and summaries from a raw voice transcript.

    A domain-specific wrapper around `extract_structured_data` configured
    exclusively for the NoteAnalysis schema and the strict extraction system prompt.

    Args:
        transcript (str): The clean text output generated by the STT model.
        allowed_tags (list[str]): List of valid predefined tags used to constrain
            the classification output.

    Returns:
        NoteAnalysis: The validated Pydantic model containing the structured note data.
    """
    return await extract_structured_data(
        user_text=transcript,
        response_model=NoteAnalysis,
        system_prompt_template=EXTRACT_JSON_SYSTEM_PROMPT,
        allowed_tags=allowed_tags,
    )


async def generate_rag_response(query: str, context: str) -> str:
    """Generates a contextual answer using the local LLM based on retrieved notes.

    Constructs a prompt combining the user's query with the aggregated context
    from the Obsidian vault and sends it to the LLM. If the model fails to
    return standard content (e.g., due to formatting constraints), it attempts
    to fall back to the internal reasoning content.

    Args:
        query (str): The user's specific question to be answered.
        context (str): The aggregated text content from the relevant markdown notes.

    Returns:
        str: The final generated response from the LLM, or an error message string
            if both the content and reasoning blocks are empty.

    Raises:
        httpx.HTTPError: If the network request to the local Ollama server fails.
        KeyError: If the API response structure is malformed or unexpected.
    """
    system_prompt = RAG_SYSTEM_PROMPT.format(context=context)

    llm_response = await _call_llm(
        system_prompt=system_prompt, user_prompt=query, temperature=0.1
    )

    content: str = llm_response["content"]
    reasoning: str = llm_response["reasoning_content"]

    if not content.strip():
        if reasoning.strip():
            logger.warning(
                "[llm] RAG content is empty. Falling back to reasoning_content."
            )
            content = reasoning
        else:
            return "❌ LLM failed to generate a response."

    return content.strip()
