x-src-volume: &src-volume "./src:/app/src"

services:
  bot:
    volumes:
      - *src-volume
      - ./migrations:/app/migrations
      - ./alembic.ini:/app/alembic.ini

  worker:
    volumes:
      - *src-volume

  scheduler:
    volumes:
      - *src-volume

  redis:
    ports:
      - "6379:6379"

  rabbitmq:
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_UI_PORT:-15672}:15672"

  postgres:
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  qdrant:
    ports:
      - "${QDRANT_PORT:-6333}:6333"
      -
  prometheus:
    ports:
      - "9090:9090"

  grafana:
    ports:
      - "3000:3000"
