from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import aiofiles

from core.config import settings
from core.exceptions import VaultIOError
from core.logger import logger
from core.metrics.definitions import BusinessMetrics
from modules.llm.schemas import NoteAnalysis


async def _write_obsidian_note(
    subfolder: str, filename: str, body: str, frontmatter: dict[str, Any] | None = None
) -> Path:
    """Asynchronously writes a .md to a specific directory within the Obsidian vault.

    Acts as a core I/O utility. Automatically handles directory creation and dynamic
    generation of YAML frontmatter if metadata is provided.

    Args:
        subfolder (str): The target subdirectory inside the Obsidian vault.
        filename (str): The name of the markdown file (must include the .md extension).
        body (str): The main markdown content of the note.
        frontmatter (dict[str, Any] | None, optional): A dictionary of metadata to be
            injected as YAML frontmatter. Defaults to None.

    Returns:
        Path: The absolute path to the created markdown file.

    Raises:
        VaultIOError: If an OS-level error occurs while writing the file to the Obsidian
         vault.
    """
    target_dir: Path = Path(settings.OBSIDIAN_DIR) / subfolder
    target_dir.mkdir(parents=True, exist_ok=True)
    filepath: Path = target_dir / filename

    content: str = ""
    if frontmatter:
        content += "---\n"
        for key, value in frontmatter.items():
            if isinstance(value, list):
                content += f"{key}:\n"
                for item in value:
                    content += f"  - {item}\n"
            else:
                content += f"{key}: {value}\n"
        content += "---\n\n"

    content += body

    try:
        async with aiofiles.open(filepath, mode="w", encoding="utf-8") as f:
            await f.write(content)
    except OSError as e:
        logger.exception(f"[obsidian] Failed to write raw note to {filepath}")
        raise VaultIOError(f"Failed to write note: {e}") from e

    logger.info(f"[obsidian] Note saved to {subfolder}: {filepath.name}")
    return filepath


async def save_raw_transcript(transcript: str, file_id: str) -> str:
    """Saves the unprocessed voice transcript to the Inbox directory.

    Generates a timestamped filename ensuring uniqueness via the file_id.
    Injects a basic 'raw_transcript' tag for easy filtering in Obsidian.

    Args:
        transcript (str): The raw text output generated by the STT model (Whisper).
        file_id (str): The unique identifier of the original voice message.

    Returns:
        str: The generated filename of the raw transcript.
    """
    timestamp: str = datetime.now(UTC).strftime("%Y%m%d_%H%M%S")
    filename: str = f"raw_voice_{timestamp}_{file_id[:8]}.md"

    await _write_obsidian_note(
        subfolder="RAW",
        filename=filename,
        body=transcript,
    )
    return filename


async def save_processed_note(analysis: NoteAnalysis, raw_filename: str) -> str:
    """Generates and saves a structured markdown note based on LLM analysis.

    Constructs a readable note containing a summary and actionable tasks.
    Dynamically builds YAML properties, establishing a native bidirectional
    Obsidian link to the original raw transcript for traceability.

    Args:
        analysis (NoteAnalysis): The Pydantic model containing the structured
            data extracted by the LLM.
        raw_filename (str): The filename of the corresponding raw transcript
            to be linked in the metadata.

    Returns:
        str: The filename of the saved processed note.

    Raises:
        VaultIOError: If an OS-level error occurs while writing the processed note to
        the Obsidian vault.
    """
    body: str = f"## Summary\n{analysis.summary}\n\n"

    if analysis.action_points:
        body += "## Action Points\n"
        for task in analysis.action_points:
            body += f"- [ ] {task}\n"

    frontmatter = "---\ntype: Analysed\n"

    if analysis.tags:
        frontmatter += "tags:\n"
        for tag in analysis.tags:
            frontmatter += f"  - {tag}\n"

    frontmatter += f"source: '[[{raw_filename}]]'\n---\n\n"

    note_content = frontmatter + body

    safe_title = analysis.title.replace("/", "_").replace("\\", "_")
    base_path = Path(settings.OBSIDIAN_DIR) / "Processed"
    file_path = base_path / f"{safe_title}.md"

    counter = 1
    while file_path.exists():
        file_path = base_path / f"{safe_title}_{counter}.md"
        counter += 1

    try:
        async with aiofiles.open(file_path, "w", encoding="utf-8") as f:
            await f.write(note_content)

        BusinessMetrics.NOTES_SAVED.inc()

        if analysis.tags:
            for tag in analysis.tags:
                BusinessMetrics.TAGS_ASSIGNED.labels(tag_name=tag).inc()

    except OSError as e:
        logger.exception(f"[obsidian] Failed to save processed note to {file_path}")
        raise VaultIOError(f"Failed to save processed note: {e}") from e

    logger.info(f"[obsidian] Processed note saved successfully: {file_path.name}")

    return file_path.name


async def read_note_content(filepath: str) -> str | None:
    """Asynchronously reads the text content of a processed note from the vault.

    Resolves the target file path within the 'Processed' directory of the Obsidian
    vault. Safely handles missing files or read errors to prevent the RAG pipeline
    from crashing due to filesystem inconsistencies.

    Args:
        filepath (str): The name or relative path of the markdown file to read.

    Returns:
        str | None: The full text content of the markdown file, or None if the
            file does not exist, is not a file, or cannot be read.
    """
    full_path = Path(settings.OBSIDIAN_DIR) / "Processed" / filepath

    if not full_path.exists() or not full_path.is_file():
        logger.warning(f"[obsidian] File not found or not a file: {full_path}")
        return None

    try:
        async with aiofiles.open(full_path, encoding="utf-8") as file:
            return await file.read()
    except OSError:
        logger.exception(f"[obsidian] Error reading file {full_path}")
        return None
