from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import aiofiles

from core.config import settings
from core.logger import logger
from modules.llm.schemas import NoteAnalysis


async def _write_obsidian_note(
    subfolder: str, filename: str, body: str, frontmatter: dict[str, Any] | None = None
) -> Path:
    """Asynchronously writes a .md to a specific directory within the Obsidian vault.

    Acts as a core I/O utility. Automatically handles directory creation and dynamic
    generation of YAML frontmatter if metadata is provided.

    Args:
        subfolder (str): The target subdirectory inside the Obsidian vault.
        filename (str): The name of the markdown file (must include the .md extension).
        body (str): The main markdown content of the note.
        frontmatter (dict[str, Any] | None, optional): A dictionary of metadata to be
            injected as YAML frontmatter. Defaults to None.

    Returns:
        Path: The absolute path to the created markdown file.
    """
    target_dir: Path = Path(settings.OBSIDIAN_DIR) / subfolder
    target_dir.mkdir(parents=True, exist_ok=True)
    filepath: Path = target_dir / filename

    content: str = ""
    if frontmatter:
        content += "---\n"
        for key, value in frontmatter.items():
            if isinstance(value, list):
                content += f"{key}:\n"
                for item in value:
                    content += f"  - {item}\n"
            else:
                content += f"{key}: {value}\n"
        content += "---\n\n"

    content += body

    async with aiofiles.open(filepath, mode="w", encoding="utf-8") as f:
        await f.write(content)

    logger.info(f"[obsidian] Note saved to {subfolder}: {filepath.name}")
    return filepath


async def save_raw_transcript(transcript: str, file_id: str) -> str:
    """Saves the unprocessed voice transcript to the Inbox directory.

    Generates a timestamped filename ensuring uniqueness via the file_id.
    Injects a basic 'raw_transcript' tag for easy filtering in Obsidian.

    Args:
        transcript (str): The raw text output generated by the STT model (Whisper).
        file_id (str): The unique identifier of the original voice message.

    Returns:
        str: The generated filename of the raw transcript.
    """
    timestamp: str = datetime.now(UTC).strftime("%Y%m%d_%H%M%S")
    filename: str = f"raw_voice_{timestamp}_{file_id[:8]}.md"

    await _write_obsidian_note(
        subfolder="RAW",
        filename=filename,
        body=transcript,
    )
    return filename


async def save_processed_note(analysis: NoteAnalysis, raw_filename: str) -> None:
    """Generates and saves a structured markdown note based on LLM analysis.

    Constructs a readable note containing a summary and actionable tasks.
    Dynamically builds YAML properties, establishing a native bidirectional
    Obsidian link to the original raw transcript for traceability.

    Args:
        analysis (NoteAnalysis): The Pydantic model containing the structured
            data extracted by the LLM.
        raw_filename (str): The filename of the corresponding raw transcript
            to be linked in the metadata.

    Returns:
        None
    """
    body: str = f"# {analysis.title}\n\n## Summary\n{analysis.summary}\n\n"

    if analysis.action_points:
        body += "## Action Points\n"
        for task in analysis.action_points:
            body += f"- [ ] {task}\n"

    safe_title: str = "".join(
        c for c in analysis.title if c.isalnum() or c in " -_"
    ).strip()
    filename: str = f"{safe_title}.md"

    metadata: dict[str, Any] = {
        "type": "Analysed",
        "tags": analysis.tags,
        "source": f'"[[{raw_filename}]]"',
    }

    await _write_obsidian_note(
        subfolder="Processed", filename=filename, body=body, frontmatter=metadata
    )
